### ISSUE TITLE
你如何确定阈值= 60和左= 60 ??

### ISSUE THREAD

**Issue by pyronlaboratory** [Python3WebSpider/CrackGeetest#10]
你好！

很棒的存储库

做得好。

我想知道一些事情..

在is_pixel_equal（）和get_gap（）函数中......

你如何确定阈值= 60和左= 60

非常感谢你的帮助！

**Comment by huxiao123** [comment]
我觉得它是使用Mac像素尺拉的距离是60

**Comment by Germey** [comment]
因为一般来说，目标滑块都在 60 像素靠右的位置，所以从 60 开始计算，是手工测量的。
