### ISSUE TITLE
拖曳验证失败后，并不会重新拖曳验证

### ISSUE THREAD

**Issue by hubinggg** [Python3WebSpider/CrackGeetest#2]
拖曳验证失败后，并不会重新拖曳验证，而是等待到timeout，直到报错？？？？
`TimeoutException                          Traceback (most recent call last)
<ipython-input-33-cedbe972f5a4> in <module>()
    216 if __name__ == '__main__':
    217     crack = CrackGeetest()
--> 218     crack.crack()

<ipython-input-33-cedbe972f5a4> in crack(self)
    204 
    205         success = self.wait.until(
--> 206             EC.text_to_be_present_in_element((By.CLASS_NAME, 'geetest_success_radar_tip_content'), '验证成功'))
    207         print(success)
    208 

~\Anaconda3\lib\site-packages\selenium\webdriver\support\wait.py in until(self, method, message)
     78             if time.time() > end_time:
     79                 break
---> 80         raise TimeoutException(message, screen, stacktrace)
     81 
     82     def until_not(self, method, message=''):

TimeoutException: Message: 
`

**Comment by Germey** [comment]
是，这块没加检测，代码用意是讲解破解思路，重试的检测可以手动后面加一下~
