### ISSUE TITLE
selenium.common.exceptions.WebDriverException

### ISSUE THREAD

**Issue by chenweigh** [Python3WebSpider/CrackGeetest#9]
selenium.common.exceptions.WebDriverException: Message: UnknownError: Cannot release a button when no button is pressed.'UnknownError: Cannot release a button when no button is pressed.' when calling method: [wdIMouse::up]

报错，我确定我的按钮的 id 是唯一的。

```
action = ActionChains(driver)
        action.click_and_hold(button).perform()
        distance = 250
        track = get_track(distance)
        for i in track:
            action.move_by_offset(xoffset=i, yoffset=0).perform()
            action.release(button).perform()
            time.sleep(0.5)
```

**Comment by qzmone** [comment]
不要提前释放按钮，等for循环结束释放按钮action.release(button).perform()
